spring:
  profiles: Eureka1
  application:
    name: Eureka
server:
  port: 2222
eureka:
  instance:
    hostname : Eur1
  client:
    registerwithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://Eur2:2223/eureka,http://Eur3:2224/eureka/

---
spring:
  profiles: Eureka1
  application:
    name: Eureka
server:
  port: 2223
eureka:
  instance:
    hostname : Eur2
  client:
    registerwithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://Eur2:2222/eureka,http://Eur3:2224/eureka/
---
spring:
  profiles: Eureka1
  application:
    name: Eureka
server:
  port: 2222
eureka:
  instance:
    hostname : Eur1
  client:
    registerwithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://Eur2:2222/eureka,http://Eur3:2223/eureka/



